swagger: '2.0'

info:
  version: '1.0'
  title: "se2_project_nathaniellee"
  description: Didactical project for software engineering 2 unitn
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE

host: se2-project-nathaniellee.herokuapp.com

basePath: /
schemes:
- https

consumes:
- application/json
produces:
- application/json

paths:
  /students:
    get:
      summary: Returns the list of all students
      # description: Description
      produces:
        - application/json
      responses:
        200:
          description: OK
        400:
          description: Bad request
        404:
          description: Not found
        500:
          description: Internal server error
  /students/{studentId}:
    get:
      summary: Returns the student with the specified id
      parameters:
        - in: path
          name: studentId
          required: true
          type: integer
          minimum: 1
          description: The id of the student
      responses:
        200:
          description: A Student object.
          schema:
            $ref: '#/definitions/Student'
        400:
          description: The specified user ID is invalid.
        404:
          description: A user with the specified ID was not found.
        500:
          description: Internal server error
        default:
          description: Unexpected error

definitions:
  Student:
    properties:
      id:
        type: integer
        example: 123456
      name:
        type: string
        example: Polpetta
    required:
      - id